langauge: node_js
before_install: nvm install v5
install: npm install blitzrk/asciidoc-blog
script: bash ./run/deploy.sh
env:
  global:
  - GH_NAME: Ben Krieger
  - GH_EMAIL: blitzrk@gmail.com
  - GH_REF: github.com/blitzrk/blitzrk.github.io.git
  - GH_BRANCH: master
  - secure: McLRtecllqL7xwYbplO00ud2fFJoO5G30UxTOFvDQiKzG7TYbA0/BILShq4jSQG6FhFAVmPldHHvUM0GLcbuXwfprqkxlpRRmxbpL2R/l8S+axbifbet65Jjp6kcvKT0vbI70TLpybZXf8sMlCI81ZYkCsHoUuyyCpVQN67YuIYuJCGAlVAObkPM0g471jwyJCy7Me24FmXpkKYPQ83QYNhkuYcCyxombi0cq6KYFKgcVaFj5HYMuVlt433po3cj5L0ZUCN/PtON8Wo23kHDiBPl+sLyKfv2QnuqqfuuClLdkBj/DofcTidtZhppzSfijkShFweIZex5dKeZieXlFTBtY61ITTKzvy76+Ky62mYlPDGCF94iG7tU9adX8iWbA1hPMEeCZTESxyPpD7WRxvyWfoTdL+pOKfc5t94xODrJtg0+qlTlZm9b8zcECOVtsOxhvfStbNpYvAj+FpfWJ87soBlORhngnBNAr05iII66NJQTTGEhggl22wntKrrg8dttSZcmGcm+BropPHAZrr7Wg/qDopF/1TxhnHK6I8BbyoPPU3m6g25b/h9t2odrtG3/eYL6XRnFbYo72+8KjfkZVunhbpDId6RsFqfkWJ5+E9pQhKc9y7NHD+Lihs7doEYmSO94IlwZHwKNrnzW47uSwHrpy04CfiIPQUwq5g0=
notifications:
  email: false
branches:
  only:
  - master
